### ISSUE TITLE
Text Input is super duper broken and doesn't pass down a ton of properties correctly

### ISSUE THREAD

**Issue by GiantRobots** [sendgrid/ui-components#112]

**Comment by Progyan1997** [comment]
Has anyone taken this issue up? If not, then I am interested. @GiantRobots  Can you specify a little more?

**Comment by GiantRobots** [comment]
@Progyan1997 Thanks for volunteering to take this work on.

This work is tangentially related to this issue as well. https://github.com/sendgrid/ui-components/issues/271 and it could serve as a good reference for updating the rest of the repo (IN short additional props like isDark, isLarge are being passed down to elements that don't support them and they don't adhere to the all lowercase convention put forward by react to get non standard attributes into elements.

Some of this was resolved in this PR https://github.com/sendgrid/ui-components/pull/190. But all of this is still probably not the best. I'd like to see any types that aren't supported by the input with a type of text to have Typescript errors. I'd also like to see attribute be a dedicated name and not a rest on the properties for textInput (breaking change)
