### ISSUE TITLE
Upload Icon type needs to be updated

### ISSUE THREAD

**Issue by mmissey** [sendgrid/ui-components#184]
Re: this design: https://sendgrid.invisionapp.com/share/3JCDVXJ9N#/screens/241371291

This icon exists in the font, but not in UI-Components.
http://styleguide.sendgrid.com/icons.html

**Comment by malgamves** [comment]
Couldn't see this problem, could you give a little more detail

**Comment by mmissey** [comment]
Sorry! This issue is out of date! This issue has already been fixed
