### ISSUE TITLE
'react-animate-height' not found

### ISSUE THREAD

**Issue by toddmoy** [sendgrid/ui-components#197]
Not sure if a bug or not, but figured I'd post this. 

After adding ui-component to a new project, when I import any component (not just an accordion) I receive this error: 

```
Could not find dependency: 'react-animate-height' relative to '/node_modules/@sendgrid/ui-components/accordion/accordion-panel.js'
```

When I add that library, I get the following: 

```
Could not find dependency: 'lodash' relative to '/node_modules/@sendgrid/ui-components/filterable-list.js'
```

Adding lodash makes it work. 

---

Here's an example: https://codesandbox.io/s/1ym1kvv0y3

**Comment by toddmoy** [comment]
Bump

**Comment by toddmoy** [comment]
Reason I'm noticing this -- I'd like to prototype UIs in CodeSandbox but can't import ui-components

**Comment by Ditofry** [comment]
I'm adding this as a topic for the internal front-end guild.  The way this project is built needs a little more love and then we will be able to manage dependencies like these a little more easily.
